version: "3"
services:
  db:
    image: postgres:16.10
    ports:
      - "${HOST_DB_PORT}:5432"
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${db_username} -d ${db_name}" ]
      interval: 2s
      retries: 3
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
  backend:
    ports:
      - "8000:8080"
    build:
      context: ./backend
      args:
        source: ${BUILD_SOURCE}
    restart: always
    networks:
      - backend_network
      - db_network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${db_name}
      DB_USER: ${db_username}
      DB_PASSWORD: ${db_password}
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
networks:
  backend_network:
  db_network: