name: Building app images
run-name: ${{ github.actor }} is building app images
on:
  push:
    branches:
      - 'feature/**'
jobs:
  build_backend:
    name: Starting process of building backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up java env
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Building image
        run: docker build ./backend

#  push_images:
#    name: Starting process of pushing images
#    needs: build_backend
#    runs-on: ubuntu-latest
#    steps:
#      - uses

