name: Building app images
run-name: ${{ github.actor }} is building app images
on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: read
  packages: write

jobs:
  build_backend:
    name: Starting process of building backend
    runs-on: ubuntu-latest
    env:
      BUILD_SOURCE: remote_build_jar
    steps:
      - uses: actions/checkout@v4
      - name: Setting up java env
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Building jar
        run: mvn -f ./backend -B clean package
      - name: Extract project version
        id: set_tag
        run: |
          cd ./backend
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "DEBUG: Detected version: '$VERSION'"
          echo "DOCKER_TAG=ghcr.io/fuukowatty/stock-market-backend:$VERSION" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.set_tag.outputs.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: source=${{ env.BUILD_SOURCE }}