name: Building app images
run-name: ${{ github.actor }} is building app images
on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: read
  packages: write

jobs:
  build_backend:
    name: Starting process of building backend
    runs-on: ubuntu-latest
    env:
      BUILD_SOURCE: remote_build_jar
    steps:
      - uses: actions/checkout@v4
      - name: Setting up java env
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Building jar
        run: mvn -f ./backend -B clean package
      - name: Extract project version
        id: get_version
        run: |
          cd ./backend
          echo PROJECT_VERSION=$(mvn -f . help:evaluate \
          -Dexpression=project.version \
          -q -DforceStdout) >> $GITHUB_OUTPUT
      - name: Building image
        run: docker build -t ghcr.io/fuukowatty/stock-market-backend:${{ steps.get_version.outputs.VERSION }} ./backend
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/fuukowatty/stock-market-backend:${{ steps.get_version.outputs.PROJECT_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max