name: Building app images
run-name: ${{ github.actor }} is building app images
on:
  push:
    branches:
      - 'feature/**'
jobs:
  build_backend:
    name: Starting process of building backend
    runs-on: ubuntu-latest
    env:
      BUILD_SOURCE: remote_build_jar
    steps:
      - uses: actions/checkout@v2
      - name: Setting up java env
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Building jar
        run: mvn -f ./backend clean package
      - name: Extract project version
        id: get_version
        run: | 
          cd ./backend
          echo PROJECT_VERSION=$(mvn -q \
          -Dexec.executable=echo \
          -Dexec.args='${project.version}' \
          --non-recursive \
          exec:exec) >> $GITHUB_ENV
      - name: Building image
        run: docker compose build -t stock-market-backend:${{ env.PROJECT_VERSION }} backend

#  push_images:
#    name: Starting process of pushing images
#    needs: build_backend
#    runs-on: ubuntu-latest
#    steps:
#      - uses

